services:
  - type: web
    name: ai-meeting-summarizer-backend
    env: python
    branch: main
    rootDir: BACKEND
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirement.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
